
package model;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ServicioAntecedentesPenalesSW", targetNamespace = "http://model/",
                  wsdlLocation =
                  "http://192.168.16.13:7101/ServidorAntecedentesJDBCSW-ServidorAntecedentesSW-context-root/ServicioAntecedentesPenalesPort?WSDL#%7Bhttp%3A%2F%2Fmodel%2F%7DServicioAntecedentesPenalesSW")
public class ServicioAntecedentesPenalesSW extends Service {

    private final static URL SERVICIOANTECEDENTESPENALESSW_WSDL_LOCATION;
    private final static WebServiceException SERVICIOANTECEDENTESPENALESSW_EXCEPTION;
    private final static QName SERVICIOANTECEDENTESPENALESSW_QNAME =
        new QName("http://model/", "ServicioAntecedentesPenalesSW");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://192.168.16.13:7101/ServidorAntecedentesJDBCSW-ServidorAntecedentesSW-context-root/ServicioAntecedentesPenalesPort?WSDL#%7Bhttp%3A%2F%2Fmodel%2F%7DServicioAntecedentesPenalesSW");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOANTECEDENTESPENALESSW_WSDL_LOCATION = url;
        SERVICIOANTECEDENTESPENALESSW_EXCEPTION = e;
    }

    public ServicioAntecedentesPenalesSW() {
        super(__getWsdlLocation(), SERVICIOANTECEDENTESPENALESSW_QNAME);
    }

    public ServicioAntecedentesPenalesSW(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOANTECEDENTESPENALESSW_QNAME, features);
    }

    public ServicioAntecedentesPenalesSW(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOANTECEDENTESPENALESSW_QNAME);
    }

    public ServicioAntecedentesPenalesSW(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOANTECEDENTESPENALESSW_QNAME, features);
    }

    public ServicioAntecedentesPenalesSW(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioAntecedentesPenalesSW(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicioAntecedentesPenales
     */
    @WebEndpoint(name = "ServicioAntecedentesPenalesPort")
    public ServicioAntecedentesPenales getServicioAntecedentesPenalesPort() {
        return super.getPort(new QName("http://model/", "ServicioAntecedentesPenalesPort"),
                             ServicioAntecedentesPenales.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioAntecedentesPenales
     */
    @WebEndpoint(name = "ServicioAntecedentesPenalesPort")
    public ServicioAntecedentesPenales getServicioAntecedentesPenalesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://model/", "ServicioAntecedentesPenalesPort"),
                             ServicioAntecedentesPenales.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOANTECEDENTESPENALESSW_EXCEPTION != null) {
            throw SERVICIOANTECEDENTESPENALESSW_EXCEPTION;
        }
        return SERVICIOANTECEDENTESPENALESSW_WSDL_LOCATION;
    }

}
