
package model;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "ServicioAntecedentesPenales", targetNamespace = "http://model/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ServicioAntecedentesPenales {


    /**
     *
     * @param arg0
     * @return
     *     returns model.Ciudadano
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darCiudadanoPorCedula", targetNamespace = "http://model/",
                    className = "model.DarCiudadanoPorCedula")
    @ResponseWrapper(localName = "darCiudadanoPorCedulaResponse", targetNamespace = "http://model/",
                     className = "model.DarCiudadanoPorCedulaResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darCiudadanoPorCedulaRequest",
            output = "http://model/ServicioAntecedentesPenales/darCiudadanoPorCedulaResponse")
    public Ciudadano darCiudadanoPorCedula(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarAntecedente", targetNamespace = "http://model/",
                    className = "model.AgregarAntecedente")
    @ResponseWrapper(localName = "agregarAntecedenteResponse", targetNamespace = "http://model/",
                     className = "model.AgregarAntecedenteResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/agregarAntecedenteRequest",
            output = "http://model/ServicioAntecedentesPenales/agregarAntecedenteResponse")
    public boolean agregarAntecedente(@WebParam(name = "arg0", targetNamespace = "") Antecedente arg0);

    /**
     *
     * @return
     *     returns java.util.List<model.TipoDocumento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darTipoDocumentos", targetNamespace = "http://model/",
                    className = "model.DarTipoDocumentos")
    @ResponseWrapper(localName = "darTipoDocumentosResponse", targetNamespace = "http://model/",
                     className = "model.DarTipoDocumentosResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darTipoDocumentosRequest",
            output = "http://model/ServicioAntecedentesPenales/darTipoDocumentosResponse")
    public List<TipoDocumento> darTipoDocumentos();

    /**
     *
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darSentenciaTotalPorCiudadano", targetNamespace = "http://model/",
                    className = "model.DarSentenciaTotalPorCiudadano")
    @ResponseWrapper(localName = "darSentenciaTotalPorCiudadanoResponse", targetNamespace = "http://model/",
                     className = "model.DarSentenciaTotalPorCiudadanoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darSentenciaTotalPorCiudadanoRequest",
            output = "http://model/ServicioAntecedentesPenales/darSentenciaTotalPorCiudadanoResponse")
    public int darSentenciaTotalPorCiudadano(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarCiudadano", targetNamespace = "http://model/",
                    className = "model.EliminarCiudadano")
    @ResponseWrapper(localName = "eliminarCiudadanoResponse", targetNamespace = "http://model/",
                     className = "model.EliminarCiudadanoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/eliminarCiudadanoRequest",
            output = "http://model/ServicioAntecedentesPenales/eliminarCiudadanoResponse")
    public boolean eliminarCiudadano(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCiudadano", targetNamespace = "http://model/",
                    className = "model.ActualizarCiudadano")
    @ResponseWrapper(localName = "actualizarCiudadanoResponse", targetNamespace = "http://model/",
                     className = "model.ActualizarCiudadanoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/actualizarCiudadanoRequest",
            output = "http://model/ServicioAntecedentesPenales/actualizarCiudadanoResponse")
    public boolean actualizarCiudadano(@WebParam(name = "arg0", targetNamespace = "") Ciudadano arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarCiudadano", targetNamespace = "http://model/",
                    className = "model.AgregarCiudadano")
    @ResponseWrapper(localName = "agregarCiudadanoResponse", targetNamespace = "http://model/",
                     className = "model.AgregarCiudadanoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/agregarCiudadanoRequest",
            output = "http://model/ServicioAntecedentesPenales/agregarCiudadanoResponse")
    public boolean agregarCiudadano(@WebParam(name = "arg0", targetNamespace = "") Ciudadano arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns model.Delito
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darDelitoPorCodigo", targetNamespace = "http://model/",
                    className = "model.DarDelitoPorCodigo")
    @ResponseWrapper(localName = "darDelitoPorCodigoResponse", targetNamespace = "http://model/",
                     className = "model.DarDelitoPorCodigoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darDelitoPorCodigoRequest",
            output = "http://model/ServicioAntecedentesPenales/darDelitoPorCodigoResponse")
    public Delito darDelitoPorCodigo(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarAntecedente", targetNamespace = "http://model/",
                    className = "model.ActualizarAntecedente")
    @ResponseWrapper(localName = "actualizarAntecedenteResponse", targetNamespace = "http://model/",
                     className = "model.ActualizarAntecedenteResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/actualizarAntecedenteRequest",
            output = "http://model/ServicioAntecedentesPenales/actualizarAntecedenteResponse")
    public boolean actualizarAntecedente(@WebParam(name = "arg0", targetNamespace = "") Antecedente arg0);

    /**
     *
     * @return
     *     returns java.util.List<model.Antecedente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darAntecedentes", targetNamespace = "http://model/",
                    className = "model.DarAntecedentes")
    @ResponseWrapper(localName = "darAntecedentesResponse", targetNamespace = "http://model/",
                     className = "model.DarAntecedentesResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darAntecedentesRequest",
            output = "http://model/ServicioAntecedentesPenales/darAntecedentesResponse")
    public List<Antecedente> darAntecedentes();

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarAntecedente", targetNamespace = "http://model/",
                    className = "model.EliminarAntecedente")
    @ResponseWrapper(localName = "eliminarAntecedenteResponse", targetNamespace = "http://model/",
                     className = "model.EliminarAntecedenteResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/eliminarAntecedenteRequest",
            output = "http://model/ServicioAntecedentesPenales/eliminarAntecedenteResponse")
    public boolean eliminarAntecedente(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns model.TipoDocumento
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darTipoDocumentoPorCodigo", targetNamespace = "http://model/",
                    className = "model.DarTipoDocumentoPorCodigo")
    @ResponseWrapper(localName = "darTipoDocumentoPorCodigoResponse", targetNamespace = "http://model/",
                     className = "model.DarTipoDocumentoPorCodigoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darTipoDocumentoPorCodigoRequest",
            output = "http://model/ServicioAntecedentesPenales/darTipoDocumentoPorCodigoResponse")
    public TipoDocumento darTipoDocumentoPorCodigo(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns model.Antecedente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darAntecedentePorId", targetNamespace = "http://model/",
                    className = "model.DarAntecedentePorId")
    @ResponseWrapper(localName = "darAntecedentePorIdResponse", targetNamespace = "http://model/",
                     className = "model.DarAntecedentePorIdResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darAntecedentePorIdRequest",
            output = "http://model/ServicioAntecedentesPenales/darAntecedentePorIdResponse")
    public Antecedente darAntecedentePorId(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<model.Antecedente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darAntecedentesPorCiudadano", targetNamespace = "http://model/",
                    className = "model.DarAntecedentesPorCiudadano")
    @ResponseWrapper(localName = "darAntecedentesPorCiudadanoResponse", targetNamespace = "http://model/",
                     className = "model.DarAntecedentesPorCiudadanoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darAntecedentesPorCiudadanoRequest",
            output = "http://model/ServicioAntecedentesPenales/darAntecedentesPorCiudadanoResponse")
    public List<Antecedente> darAntecedentesPorCiudadano(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<model.Antecedente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darAntecedentesPorDelito", targetNamespace = "http://model/",
                    className = "model.DarAntecedentesPorDelito")
    @ResponseWrapper(localName = "darAntecedentesPorDelitoResponse", targetNamespace = "http://model/",
                     className = "model.DarAntecedentesPorDelitoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darAntecedentesPorDelitoRequest",
            output = "http://model/ServicioAntecedentesPenales/darAntecedentesPorDelitoResponse")
    public List<Antecedente> darAntecedentesPorDelito(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<model.Antecedente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darAntecedentesPorCiudadanoYDelito", targetNamespace = "http://model/",
                    className = "model.DarAntecedentesPorCiudadanoYDelito")
    @ResponseWrapper(localName = "darAntecedentesPorCiudadanoYDelitoResponse", targetNamespace = "http://model/",
                     className = "model.DarAntecedentesPorCiudadanoYDelitoResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darAntecedentesPorCiudadanoYDelitoRequest",
            output = "http://model/ServicioAntecedentesPenales/darAntecedentesPorCiudadanoYDelitoResponse")
    public List<Antecedente> darAntecedentesPorCiudadanoYDelito(@WebParam(name = "arg0", targetNamespace = "")
                                                                String arg0,
                                                                @WebParam(name = "arg1", targetNamespace = "")
                                                                int arg1);

    /**
     *
     * @return
     *     returns java.util.List<model.Delito>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darDelitos", targetNamespace = "http://model/", className = "model.DarDelitos")
    @ResponseWrapper(localName = "darDelitosResponse", targetNamespace = "http://model/",
                     className = "model.DarDelitosResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darDelitosRequest",
            output = "http://model/ServicioAntecedentesPenales/darDelitosResponse")
    public List<Delito> darDelitos();

    /**
     *
     * @return
     *     returns java.util.List<model.Ciudadano>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "darCiudadanos", targetNamespace = "http://model/", className = "model.DarCiudadanos")
    @ResponseWrapper(localName = "darCiudadanosResponse", targetNamespace = "http://model/",
                     className = "model.DarCiudadanosResponse")
    @Action(input = "http://model/ServicioAntecedentesPenales/darCiudadanosRequest",
            output = "http://model/ServicioAntecedentesPenales/darCiudadanosResponse")
    public List<Ciudadano> darCiudadanos();

}
